"""Canonical PEX protocol types, versioned and shared across bridge, supervisor, and UI."""

from pex_protocol.actions import InterventionType, ProposedAction, RiskLevel
from pex_protocol.capabilities import AdapterCapabilities, AdapterSupportLabel, ControlGranularity
from pex_protocol.context import (
    ClaimVerificationRequest,
    ContextBundle,
    ContextHandoffRequest,
    ContextItem,
    HandoffAssimilationEvidence,
    HumanDecisionRequest,
    ProgressEvidenceReference,
    ProgressReport,
)
from pex_protocol.enums import (
    Authority,
    AutonomyLevel,
    DecisionSource,
    DecisionStatus,
    EventPhase,
    EventType,
    HarnessType,
    PolicyVerdict,
    Sensitivity,
    SessionStatus,
    SourceKind,
)
from pex_protocol.fingerprint import AgentFingerprint
from pex_protocol.goal import Decision, Goal
from pex_protocol.intervention import Intervention
from pex_protocol.overlay import Overlay, OverlayDiff
from pex_protocol.project_identity import (
    PathPlatform,
    PhysicalIdentityProof,
    ProjectIdentity,
    ProjectLocator,
    ProjectLocatorKind,
    ProjectOrigin,
    canonical_absolute_path,
    same_absolute_path,
    same_project_locator,
)
from pex_protocol.session import HarnessEvent, HarnessSession
from pex_protocol.supervisor import SupervisorRequest, SupervisorResult, TrajectoryScores
from pex_protocol.verification import (
    EvidenceGatheringReceipt,
    EvidenceGatheringState,
    PytestInvocation,
    PytestInvocationScope,
    VerificationBackendKind,
    VerificationExecutionReceipt,
    VerificationExecutionResult,
    VerificationProbe,
    VerificationProbeKind,
    classify_pytest_argv,
    classify_pytest_invocation,
)

SCHEMA_VERSION = "1"

__all__ = [
    "SCHEMA_VERSION",
    "AdapterCapabilities",
    "AdapterSupportLabel",
    "AgentFingerprint",
    "Authority",
    "AutonomyLevel",
    "ClaimVerificationRequest",
    "ContextBundle",
    "ContextHandoffRequest",
    "ContextItem",
    "HandoffAssimilationEvidence",
    "ContextKind",
    "ControlGranularity",
    "Decision",
    "DecisionSource",
    "DecisionStatus",
    "EventPhase",
    "EventType",
    "EvidenceGatheringReceipt",
    "EvidenceGatheringState",
    "Goal",
    "HarnessEvent",
    "HarnessSession",
    "HarnessType",
    "HumanDecisionRequest",
    "Intervention",
    "InterventionType",
    "Overlay",
    "OverlayDiff",
    "PathPlatform",
    "PhysicalIdentityProof",
    "PolicyVerdict",
    "ProgressEvidenceReference",
    "ProgressReport",
    "ProjectIdentity",
    "ProjectLocator",
    "ProjectLocatorKind",
    "ProjectOrigin",
    "canonical_absolute_path",
    "same_absolute_path",
    "ProposedAction",
    "PytestInvocation",
    "PytestInvocationScope",
    "RiskLevel",
    "Sensitivity",
    "SessionStatus",
    "SourceKind",
    "SupervisorRequest",
    "SupervisorResult",
    "TrajectoryScores",
    "VerificationBackendKind",
    "VerificationExecutionReceipt",
    "VerificationExecutionResult",
    "VerificationProbe",
    "VerificationProbeKind",
    "classify_pytest_argv",
    "classify_pytest_invocation",
    "same_project_locator",
]
